import type { Metadata } from "next";
import { Anonymous_Pro } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import Main from "../components/Main";
import Footer from "../components/Footer";

const anonpro = Anonymous_Pro({
  subsets: ['latin'],
  weight: ['400', '700'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={anonpro.className}>
        <Header />
        <Main/>
        {/* {children} */}
        <Footer />
      </body>
    </html>
  );
}
